### ISSUE TITLE
Update compatibility with newer version of NUnit

### ISSUE THREAD

**Issue by Sc0tTyXL** [zastrowm/NUnit.ApplicationDomain#26]
Hello,

IMHO it is a bad idea to use application bindings, we only use them if nothing else is feasable.

This package hasn't been updated in a while.
Could it be updated to be compatible with a newer version of NUnit.Framework ?

Thank you

**Comment by zastrowm** [comment]
[version 12.0.0](https://www.nuget.org/packages/NUnit.ApplicationDomain/12.0.0) now uses the latest version of nunit.
